model:
  _convert_: all
  img_size:
  - 32
  - 128
  max_label_length: 35
  charset_train: 0123456789"'‘’“”—–,.:;`?-‾_!#$%&()*+/<=>@[]^{|}~\।॥ঀঁংঃঅআইঈউঊঋঌএঐওঔকখগঘঙচছজঝঞটঠডঢণতথদধনপফবভমযরলশষসহ়ঽািীুূৃৄেৈোৌ্ৎৗড়ঢ়য়ৠৡৢৣ০১২৩৪৫৬৭৮৯ৰৱ৲৳৴৵৶৷৸৹৺৻ৼ৽
    ‌‍
  charset_test: 0123456789"'‘’“”—–,.:;`?-‾_!#$%&()*+/<=>@[]^{|}~\।॥ঀঁংঃঅআইঈউঊঋঌএঐওঔকখগঘঙচছজঝঞটঠডঢণতথদধনপফবভমযরলশষসহ়ঽািীুূৃৄেৈোৌ্ৎৗড়ঢ়য়ৠৡৢৣ০১২৩৪৫৬৭৮৯ৰৱ৲৳৴৵৶৷৸৹৺৻ৼ৽
    ‌‍
  batch_size: 128
  weight_decay: 0.0
  warmup_pct: 0.075
  name: parseq
  _target_: strhub.models.parseq.system.PARSeq
  patch_size:
  - 4
  - 8
  embed_dim: 384
  enc_num_heads: 6
  enc_mlp_ratio: 4
  enc_depth: 12
  dec_num_heads: 12
  dec_mlp_ratio: 4
  dec_depth: 1
  lr: 1.0e-05
  perm_num: 12
  perm_forward: true
  perm_mirrored: true
  dropout: 0.1
  decode_ar: true
  refine_iters: 1
data:
  _target_: strhub.data.module.SceneTextDataModule
  root_dir: /ssd_scratch/cvit/lalitha/data
  train_dir: real
  batch_size: ${model.batch_size}
  img_size: ${model.img_size}
  charset_train: ${model.charset_train}
  charset_test: ${model.charset_test}
  max_label_length: ${model.max_label_length}
  remove_whitespace: true
  normalize_unicode: true
  augment: true
  num_workers: 8
trainer:
  _target_: pytorch_lightning.Trainer
  _convert_: all
  check_val_every_n_epoch: 1
  max_epochs: 800
  gradient_clip_val: 20
  accelerator: gpu
  devices: 2
ckpt_path: null
pretrained: null
